### ISSUE TITLE
下载0701报错

### ISSUE THREAD

**Issue by sainting4** [xx025/yanx#29]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "fastapi\applications.py", line 276, in __call__
  File "starlette\applications.py", line 122, in __call__
  File "starlette\middleware\errors.py", line 149, in __call__
  File "starlette\middleware\sessions.py", line 86, in __call__
  File "starlette\middleware\cors.py", line 76, in __call__
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 718, in __call__
  File "starlette\routing.py", line 341, in handle
  File "starlette\routing.py", line 82, in app
  File "fastapi\routing.py", line 289, in app
  File "yweb\main.py", line 141, in websocket_endpoint
  File "yweb\tools.py", line 6, in create_file_name
KeyError: '0701'

**Comment by xx025** [comment]
这个问题在最新的版本中已经修复  可前往[releases](https://github.com/xx025/yanx/releases/latest) 查看
